import random
import streamlit as st
import s3fs

from app import image_url


def main():

    fs = s3fs.S3FileSystem(anon=False)

    n_rows = 2
    n_cols = 5

    st.set_page_config(
        page_title="GAN generated galaxies",
        page_icon=":milky_way:",
        layout="wide"
    )
    st.title(":milky_way: GAN-generated galaxies")

    text = """Galaxy images generated by a generative adversarial neural network 
    trained to mimic the EAGLE galaxies"""
    st.markdown(text)

    st.button("Load random examples")

    cols = st.columns(n_cols)

    for col in cols:
        with col:
            for i in range(n_rows):
                image_number = random.randint(0, 45578)
                url = image_url("fake", image_number)
                with fs.open(url, 'rb') as f:
                    st.image(f.read(), use_column_width=True)


if __name__ == "__main__":
    main()
